{"name":"",
 "dns":"",
 "desc":"",
 "specs":"",
 "catchies":"",
 "roadmapTodos":"",
 "architecture":"",
 "people":{"client_-_tpl_-_person":{}},
 "sitemap":{"sections":{"main":{"id":"main",
							   "title":"Main",
							   "desc":"",
							   "imgSrc":"images\/Main.jpg",
							   "top":"581px","left":"365px","width":"414px","height":"431px",
							   "frames":{"page1":{"id":"page1",
								   				  "title":"CALENDAR DETAIL VIEW",
								   				  "desc":"",
								   				  "top":"581px","left":"365px","width":"414px","height":"431px",
								   				  "link":"calendar\/detail\/view",
								   				  "state":"inprogress",
								   				  "progress":"15",
								   				  "features":{"feature1":{"specs":{"spec1":{"title":"","desc":""}},
								   					  					  "bugs":{"bug1":{"title":"","useCaseDesc":"","state":"inprogress"}},
								   					  					  "tests":{"test1":{"title":"","desc":"","state":"inprogress"}}}}}
								   				  
							   			}
								}
					}
			}
}